# General config file

# PATHS (relative to program root dir)
[paths]
questions = "src/checkmyc/config/questions.toml"
llm = "src/checkmyc/config/llm.toml"
# -cf to enable the following paths
output_path = "output"
schema_path = "src/checkmyc/data/json_schema"
programs_path = "resources/sources"
exam_text_path = "resources"
sys_prompt_path = "src/checkmyc/data/prompts/system"
usr_prompt_path = "src/checkmyc/data/prompts/user"

# SCORE GENERATION
[weights.high]
plus  = 0   # Valore per goodness: "+"
minus = -2.0  # Valore per goodness: "-"

[weights.medium]
plus  = 0
minus = -1.0

[weights.low]
plus  = 0
minus = -0.5

# COMBINED RESULT
[combined_weights]
llm = 4.0
tests = 6.0